4.2.1から4.2.2へのアップデートに対応
EC-CUBE/eccube-update-plugin pull request #31
Opened 2023-06-16 02:14 UTC by shinya

4.2.2のリリースに伴い、こちらのプラグインの対応を行いました。

2023-06-22 01:38 UTC, chihiro-adachi commented
@shinya 
replace_version.shの設定値について、READMEの更新をお願いします。

2023-06-22 01:39 UTC, chihiro-adachi requested changes

2023-06-22 01:39 UTC, chihiro-adachi commented on bin/update_file_hash.sh
> +#curl https://downloads.ec-cube.net/src/eccube-${TO}.tar.gz | tar xz --strip-components 1
こちらは戻しておいていただければと思います

2023-06-22 01:45 UTC, chihiro-adachi commented
マージ後、こちらのレポジトリでもリリースタグ切っていただければと。

2023-06-23 08:02 UTC, shinya commented
@chihiro-adachi 
こちら更新しましたので再度確認お願いします

2023-06-26 04:35 UTC, chihiro-adachi requested changes

2023-06-26 04:35 UTC, chihiro-adachi commented on README.md
> +もし、テスト用にPreReleaseのバージョンなどで試したい場合は、変数の値を適切なものに書き換えてください。
@shinya 
パッケージのダウンロードはgithubのリリースタグからのユースケースが多くなると思うので、FROM/TOともにバージョン番号ではなくURLにしてしまったらどうでしょう。

2023-06-26 04:35 UTC, chihiro-adachi commented on README.md
> +NEXT_VERSIONには、アップデート後に変わるバージョン（From-Toでいうとなるもの）を指定します。
@shinya 
`From-Toでいうとなるもの` ちょっと意味が分かりづらいです。何かtypeしてる？

2023-06-26 04:35 UTC, chihiro-adachi commented on README.md
> +NEXT_VERSIONには、アップデート後に変わるバージョン（From-Toでいうとなるもの）を指定します。
NEXT_VERSIONには、アップデート後のバージョンを指定します。

でよいかと。

2023-06-26 04:35 UTC, chihiro-adachi commented on README.md
> -bin/replace_version.sh
@shinya 
スクリプト実行の記述が消えてますね

2023-06-26 07:36 UTC, shinya commented on README.md
> +もし、テスト用にPreReleaseのバージョンなどで試したい場合は、変数の値を適切なものに書き換えてください。
こちらGithubを参照するように書き換えました。
またそれに合わせて、FROM/TOの書き方も補足入れました。

2023-06-26 07:36 UTC, shinya commented on README.md
> +NEXT_VERSIONには、アップデート後に変わるバージョン（From-Toでいうとなるもの）を指定します。
変更反映しました。

2023-06-26 07:36 UTC, shinya commented on README.md
> -bin/replace_version.sh
こちら消した部分戻しておきました。

2023-06-26 21:52 UTC, chihiro-adachi commented
@shinya 
update_file.tar.gzが更新されているようですが、本体パッケージに何か更新あったのでしょうか？

2023-06-27 01:20 UTC, shinya commented
@chihiro-adachi 
シェルの修正（URLの部分のみ）をしたので再実行したほうが良いかと思い作り直してました。
Revertしたので再度確認お願いします。

2023-06-27 02:21 UTC, chihiro-adachi commented
@shinya 
update_file.shは、`EC-CUBE本体のパッケージの更新ファイル`を作るスクリプトなので、本体側に変更なければ実行は不要です。

2023-06-27 02:22 UTC, chihiro-adachi approved these changes

2023-06-27 02:35 UTC, merged